title:       "Agent-Based Modelling and Geographical Information Systems: A Practical Primer"
keywords:    "ABM, agent-based modelling, GIS, GISc, geography, spatial science"
description: "A textbook on the use of agent-based modelling for simulating geographical systems"
source_link: "https://github.com/abmgis/abmgis"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#00A4D8' #'#5681B8'
  green:     '#9bcf2f'
  purple:    '#66306A'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

